insert into "Cars"(brand, model, power, photo, location) values
       (
         'Kia',
	 'Mohave',
	 '250л.с.',
	 'mohave',
	 'https://yandex.ru/maps/-/CCgReG~2'
       ),
       (
         'Audi',
	 'Q7',
	 '250л.с.',
	 'q7',
	 'https://yandex.ru/maps/-/CCgeLzm'
       ),
       (
         'BMW',
	 'X5',
	 '250л.с.',
	 'x5',
	 'https://yandex.ru/maps/-/CCgRe-7p'
       ),
       (
         'Chevrolet',
	 'Tahoe',
	 '425л.с.',
	 'tahoe',
	 'https://yandex.ru/maps/-/CCgRiQ0G'
       ),
       (
         'Mitsubishi',
	 'Outlander',
	 '150л.с.',
	 'outlander',
	 'https://yandex.ru/maps/-/CCgRiK4T'
       ),
       (
         'Toyota',
	 'Land Cruiser 200',
	 '250л.с.',
	 'cruiser200',
	 'https://yandex.ru/maps/-/CCgRiSy-'
       ),
       (
         'Renault',
	 'Duster',
	 '109л.с.',
	 'duster',
	 'https://yandex.ru/maps/-/CCgRi8-F'
       ),
       (
         'Nissan',
	 'Pathfinder',
	 '170л.с.',
	 'pathfinder',
	 'https://yandex.ru/maps/-/CCgRiT7M'
       )       
;
